# Generated by Django 5.2.8 on 2025-11-17 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Team",
            fields=[
                ("team_id", models.AutoField(primary_key=True, serialize=False)),
                ("name1", models.CharField(max_length=100)),
                ("name2", models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Track",
            fields=[
                ("track_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "name",
                    models.CharField(
                        choices=[("PD", "PD"), ("BE", "BE"), ("FE", "FE")],
                        max_length=10,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Letter",
            fields=[
                ("letter_id", models.AutoField(primary_key=True, serialize=False)),
                ("writer", models.CharField(max_length=100)),
                ("content", models.TextField()),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="letters",
                        to="main.team",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="team",
            name="track",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="teams",
                to="main.track",
            ),
        ),
    ]
