# Generated by Django 5.2.8 on 2025-11-18 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="track",
            name="name",
            field=models.CharField(
                choices=[("PD", "PD"), ("BE", "BE"), ("FE", "FE"), ("ALL", "ALL")],
                max_length=10,
            ),
        ),
    ]
